import numpy as np
a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(a.shape)
print(a[1,2])
print(b[3:])
print(a.ndim)
c = np.ones((2,3))
print(c)
d = np.zeros((5,8))
e = np.empty((4, 8))
print(e)
f = np.linspace(0, 20, num = 10)
print(f)